@Library('first-library') 
pipeline {
    agent any
    
    stages {
        stage('shared library') {
            steps {
                script {
                    sh """
                    echo "This is the second shared library"
                    """
                }
            }
        }
    }
}