@Library('first-library') _
pipeline {
    agent any
    
    stages {
        stage('local') {
            steps {
                script {
                    sh 'echo "This is the first shared library"'
                }
            }
        }
        stage('library') {
            steps {
                firstFunction()
            }
        }
        stage('trigger') {
            steps {
                build job: 'fuck', propagate: true
            }
        }
    }
}
